@baseUrl=http://localhost:5000/api/v1/authors

GET {{baseUrl}}

###

GET {{baseUrl}}/66d48f77fb76cfc4aa412b46

###

POST {{baseUrl}}
Content-Type: application/json

{"name": "Pinco",
 "surname": "Pallino",
 "email": "qwer@qwer.com",
 "avatar": ""
}

###

PUT  {{baseUrl}}/66d49ad7afc4f99252a9535f
Content-Type: application/json

{"name": "Pinco",
 "surname": "Pallone",
 "email": "qwer@qwer.com",
 "avatar": "https://picsum.photos/40"
}

###

DELETE  {{baseUrl}}/66d49ad7afc4f99252a9535f
