@baseUrl=http://localhost:5000/api/v1/blogPosts

GET {{baseUrl}}

###

GET {{baseUrl}}/66dd7ab78fa53fac2ef2a726

###

POST {{baseUrl}}
Content-Type: application/json

{"category": "Categoria 3",
 "title": "un bel viaggio",
 "cover": "",
 "readTime": {
    "value" : 10,
    "unit": "min"
 },
 "author": "66d87cf21b95b043b606ff5d",
 "content": "kjbfhbuerbw  werh iucwiuh iwiugwe iuiuw egiu gweiug iugweriug iuwg"
}

###

PUT  {{baseUrl}}/66d4a504a35baa9c248619aa
Content-Type: application/json

{"category": "Studio",
 "title": "Un bellissimo corso",
 "cover": "",
 "readTime": {
    "value" : 15,
    "unit": "min"
 },
 "author": "66d48f77fb76cfc4aa412b46",
 "content": "bhuiuefaiu kjbacu viguygknbv abiugcd ahgjhvdv sakbjv lkncasghcskjacsnahcsiu hfihi vhiirvy"
}


###

DELETE  {{baseUrl}}/66d4a504a35baa9c248617gf

###

GET http://localhost:5000/api/v1/blogPosts?title=viaggio